# ============================================================
# Vitta - Configuraci�n de base de datos PostgreSQL (Neon)
# ============================================================
spring.datasource.url=jdbc:postgresql://ep-plain-union-at5w8gzx-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_r4yTAmP7fKSM
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# JPA / Hibernate
# ============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
